class Program6
{
	 public static void main(String[] args)
	{
		System.out.println("MAIN METHOD START !!");
		
		display();	// call for display method 
		display();
		display();
		System.out.println("MAIN METHOD END !!");
	}
	
	public static void display()
	{
		System.out.println("DISPLAY METHOD 1 ");
		System.out.println("DISPLAY METHOD 2 ");
		System.out.println("DISPLAY METHOD 3 ");
		System.out.println("DISPLAY METHOD 4 ");
		
	}	
	
}